[package]
name = "libzmq"
version = "0.1.0"
authors = ["jean-airoldie <25088801+jean-airoldie@users.noreply.github.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
autobenches = false

[dependencies]
libc = "0.2"
serde = { version = "1.0", features = ["derive"] }
lazy_static = "1.3.0"
failure = "0.1"
libzmq-sys = { path = "../libzmq-sys", features = ["draft"] }
bitflags = "1.0.4"
static_assertions = "0.3"
serde-humantime = "0.1"

[dev-dependencies]
rand = "0.6"
rand_isaac = "0.1.1"
rand_core = "0.4"
criterion = "0.2"

[[bench]]
name = "bench_main"
harness = false
